a = print(input("Digite algo:"))
print(type(a))
print("numero",a.isnumeric())
print("maiscula",a.isupper())
print("espaço",a.isspace())
print("minuscula",a.islower())
print("",a.isupper())
print("",a.isalnum())